local h = require("harness")

local function scratch(lines, ft, col)
  h.feed("<Esc>", "xt")
  vim.cmd.enew({ bang = true })
  vim.bo.filetype = ft or "c"
  vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)
  vim.api.nvim_win_set_cursor(0, { 1, col or 0 })
end

local function lines()
  return vim.api.nvim_buf_get_lines(0, 0, -1, false)
end

h.test("leader slash and gcc round-trip while tracking the original character", function()
  scratch({ "int a = 1;" }, "c", 4)
  h.feed(" /", "xt")
  h.eq({ "// int a = 1;" }, lines())
  h.eq({ 1, 7 }, vim.api.nvim_win_get_cursor(0))
  h.feed("gcc", "xt")
  h.eq({ "int a = 1;" }, lines())
  h.eq({ 1, 4 }, vim.api.nvim_win_get_cursor(0))
end)

h.test("counts and dot repeat retain line toggle behavior", function()
  scratch({ "int a;", "int b;", "int c;" })
  h.feed("2 /", "xt")
  h.eq({ "// int a;", "// int b;", "int c;" }, lines())
  scratch({ "int a;", "int b;" })
  h.feed(" /j.", "xt")
  h.eq({ "// int a;", "// int b;" }, lines())
end)

h.test("visual selection stays active for immediate repeated toggles", function()
  scratch({ "int a;", "int b;", "int c;" })
  h.feed("Vj /", "xt")
  h.eq("V", vim.fn.mode())
  h.eq({ "// int a;", "// int b;", "int c;" }, lines())
  h.feed(" /", "xt")
  h.eq("V", vim.fn.mode())
  h.eq({ "int a;", "int b;", "int c;" }, lines())
  h.feed("<Esc>", "xt")
end)

h.test("block toggle and automatic uncomment round-trip", function()
  scratch({ "int a;" })
  h.feed("gbc", "xt")
  h.eq({ "/* int a; */" }, lines())
  h.feed("gcu", "xt")
  h.eq({ "int a;" }, lines())
end)

h.test("force operations and inversion distinguish mixed comment states", function()
  scratch({ "int a;", "// int b;" })
  h.feed("VjgCC<Esc>", "xt")
  h.eq({ "// int a;", "// // int b;" }, lines())
  h.feed("ggVjgCU<Esc>", "xt")
  h.eq({ "int a;", "// int b;" }, lines())
  h.feed("ggVjgcI<Esc>", "xt")
  h.eq({ "// int a;", "int b;" }, lines())
end)

h.test("insertion helpers use Celeste after LazyVim loads", function()
  for _, key in ipairs({ "gco", "gcO", "gcA" }) do
    local mapping = vim.fn.maparg(key, "n", false, true)
    h.eq(true, (mapping.rhs or ""):find("celeste_comment", 1, true) ~= nil, key .. " is owned by Celeste")
  end
  scratch({ "int a;" })
  h.feed("gco", "xt")
  h.eq({ "int a;", "// " }, lines())
  scratch({ "int a;" })
  h.feed("gcO", "xt")
  h.eq({ "// ", "int a;" }, lines())
  scratch({ "int a;" })
  h.feed("gcA", "xt")
  h.eq({ "int a; // " }, lines())
end)

h.test("insert toggle preserves editing position for both Alt variants", function()
  for _, key in ipairs({ "<M-/>", "<M-_>" }) do
    scratch({ "int a;" }, "c", 4)
    h.feed("i" .. key .. "x<Esc>", "xt")
    h.eq({ "// int xa;" }, lines())
  end
end)

h.test("TSX resolves JSX markup separately from TypeScript code", function()
  require("lazy").load({ plugins = { "nvim-treesitter" } })
  local original = { "const x = (", "  <div>Hello</div>", ");" }
  scratch(original, "typescriptreact")
  local parser = vim.treesitter.get_parser(0, "tsx")
  parser:parse()
  vim.api.nvim_win_set_cursor(0, { 2, 2 })
  h.feed(" /", "xt")
  h.eq("  {/* <div>Hello</div> */}", lines()[2])
  parser:parse()
  h.feed(" /", "xt")
  h.eq(original, lines())
  vim.api.nvim_win_set_cursor(0, { 1, 0 })
  h.feed(" /", "xt")
  h.eq("// const x = (", lines()[1])
end)

h.test("only Celeste loads and the project search shortcut survives", function()
  h.eq(nil, package.loaded["ts-comments"])
  h.eq(true, package.loaded["celeste_comment"] ~= nil)
  h.eq("Grep (Root Dir)", vim.fn.maparg(" sg", "n", false, true).desc)
end)
